[package]
name = "bad-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

bad-types = { path = "../bad-types" }
bad-interpreter = { path = "../bad-interpreter" }

im = "15.1.0"
fxhash = "0.2.1"
